### ISSUE TITLE
无法在Hexo文章页面调用

### ISSUE THREAD

**Issue by Magstic** [MoePlayer/hexo-tag-aplayer#120]
这是我的调用方式：
{% aplayer "XX" "XX" "https://xx.xx/xxx.mp3" %}
（有无引号均异常）

环境是Hexo的butterfly。
音频文件在服务器中，可正常外部访问。
文章页面无法调用。该显示播放器的地方是一片空白。
相关设置均有调整，但是依旧是空白。
不知有没有系统的解决方法？

网易云音乐虽然是正常调用的，但是地区限制以及曲库不全的问题不想使用。

**Comment by zengtianli** [comment]
你好，我遇到了一样的问题

**Comment by Magstic** [comment]
@zengtianli 
你好，我现在已经不再使用该插件；原因是美观性虽有，预加载选项卡确不生效的，以至于频宽分配异常，拖慢页面。
我已经忘记了自己是如何解决的这个问题，不过相关设置应该还在我的配置文件内，我将检索到的相关内容复制在下面：

**在_config.yml中添加如下内容：**
```
# 音樂擴充
aplayer:
  cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js  # 引用 APlayer.js 外部 CDN 地址 (默认不开启)
  style_cdn: https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css
  meting: true       # MetingJS 支持
  meting_cdn: https://cdn.jsdelivr.net/npm/meting/dist/Meting.min.js # 引用 Meting.js 外部 CDN 地址 (默认不开启)
```

**在_config.butterfly.yml中添加如下内容：**
```
aplayerInject:
  enable: true
  per_page: true
```
