### ISSUE TITLE
beta.5版本应该怎么使用

### ISSUE THREAD

**Issue by MonoLogueChi** [MoePlayer/hexo-tag-aplayer#32]
我用npm命令安装了beta.5版本之后生成文章的时候报错，检查之后发现beta.5版本的包里没有index.js，再一看lib和common也没有，最后只能退回beta.4版本。这个是作者打包失误还是我使用的姿势有问题啊

**Comment by grzhan** [comment]
你好，`3.0-beta.5` 应该是在打包发布的过程中出现了问题，请更新到 `3.0.0-beta.6`
此外，3.0 还是 beta 版本，如果遇到问题请及时反馈。

**Comment by MonoLogueChi** [comment]
刚才更新了beta.6，Aplayer失效，原本应该是代码部分变成了
```
<script>
    console.error("TypeError: Cannot read property '_id' of undefined");
</script>
```
以前应该是
```
<div id="aplayer-UMFNbAmX" class="aplayer aplayer-tag-marker" style="margin-bottom: 20px;">
            <pre class="aplayer-lrc-content"></pre>
        </div>
        <script>
          var ap = new APlayer({
            element: document.getElementById("aplayer-UMFNbAmX"),
            narrow: false,
            autoplay: true,
            showlrc: true,
            music: {
              title: "大漠英雄",
              author: "成龙",
              url: "https://t1.aixinxi.net/o_1c4ckoamk6pt19d01bpi28r1rh0a.ogg",
              pic: "",
              lrc: "https://t1.aixinxi.net/o_1c4ckse89kial1s18ue13051p8qa.txt",
            }
          });
          window.aplayers || (window.aplayers = []);
          window.aplayers.push(ap);
        </script>
```

错误
```
TypeError: Cannot read property '_id' of undefined
    at APlayerTag.generate (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\hexo-tag-aplayer\lib\tag\player.js:102:116)
    at Object.<anonymous> (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\hexo-tag-aplayer\index.js:122:22)
    at NunjucksTag._run (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\hexo\lib\extend\tag.js:120:18)
    at NunjucksTag.run (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\hexo\lib\extend\tag.js:116:15)
    at Template.root [as rootRenderFunc] (eval at _compile (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:617:18), <anonymous>:9:67)
    at Template.render (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:540:10)
    at Environment.renderString (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\hexo\node_modules\nunjucks\src\environment.js:364:17)
    at Promise (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\hexo\lib\extend\tag.js:66:9)
    at Promise._execute (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\bluebird\js\release\debuggability.js:300:9)
    at Promise._resolveFromExecutor (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\bluebird\js\release\promise.js:483:18)
    at new Promise (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\bluebird\js\release\promise.js:79:10)
    at Tag.render (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\hexo\lib\extend\tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\hexo\lib\hexo\post.js:260:16)
    at Promise.then.then.result (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\hexo\lib\hexo\render.js:65:19)
    at tryCatcher (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\MonoLogueChi\Documents\Hexo\blog\node_modules\bluebird\js\release\async.js:17:14)
```
config配置
```
aplayer:
  script_dir: assets/js                        # Public 目录下脚本目录路径，默认: 'assets/js'
  cdn: https://cdnjs.cat.net/ajax/libs/aplayer/1.6.0/APlayer.min.js  # 引用 APlayer.js 外部 CDN 地址 (默认不开启)
  meting: true                                  # MetingJS 支持
  #meting_api: http://xxx/api.php
  meting_cdn: https://cdn.jsdelivr.net/npm/meting@latest/dist/Meting.min.js # 引用 Meting.js 外部 CDN 地址 (默认不开启)
  asset_inject: true                            # 自动插入 Aplayer.js 与 Meting.js 资源脚本, 默认开启
```
文章内容
```
{% aplayer "大漠英雄" "成龙" "https://t1.aixinxi.net/o_1c4ckoamk6pt19d01bpi28r1rh0a.ogg" "autoplay" "lrc: https://t1.aixinxi.net/o_1c4ckse89kial1s18ue13051p8qa.txt" %}
```
